from django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('home/',views.home,name='home'),
    path('profile/',views.profile,name='profile'),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('adminhome/',views.adminhome,name='adminhome'),
    path('userlist/',views.userlist,name='userlist'),
    path('deleteuser/<int:id>/',views.deleteuser,name='deleteuser'),
    path('sregister/',views.sregister,name='sregister'),
    path('slogin/',views.slogin,name='slogin'),
    path('shome/',views.shome,name='shome'),
    path('sprofile/',views.sprofile,name='sprofile'),
    path('seditprofile/',views.seditprofile,name='seditprofile'),
    path('saddproduct/',views.saddproduct,name='saddproduct'),
    path('sproductlist/',views.sproductlist,name='sproductlist'),
    path('sdeleteproduct/<int:id>/',views.sdeleteproduct,name='sdeleteproduct'),
    path('seditproduct/<int:id>/',views.seditproduct,name='seditproduct'),
    path('logout/',views.logout,name='logout'),
    path('sellerlist/',views.sellerlist,name='sellerlist'),
    path('userproductlist/',views.userproductlist,name='userproductlist'),
    path('otp/',views.otp,name='otp'),
    path('addtocart/<int:id>/',views.addtocart,name='addtocart'),
    path('cartlist/',views.cartlist,name='cartlist'),
    path('buyitem/<int:id>/',views.buyitem,name='buyitem'),
    path('paylist/',views.paylist,name='paylist'),
    path('logout/',views.logout,name='logout'),
    path('about/',views.about,name='about'),
    path('buy_submit/<int:id>/', views.submit_buyitem, name='submit_buyitem'),
    path('deleteseller/<int:id>/',views.deleteseller,name='deleteseller'),
    path('orders/', views.orders, name='orders'),
    path('deliveryregister/', views.deliveryregister, name='deliveryregister'),
    path('deliverylogin/', views.deliverylogin, name='deliverylogin'),
    path('deliveryhome/', views.deliveryhome, name='deliveryhome'),
    path('deliverypersonlist/', views.deliverypersonlist, name='deliverypersonlist'),
    path('approvedeliveryperson/<int:id>/', views.approvedeliveryperson, name='approvedeliveryperson'),
    path('assigndelivery/<int:id>/', views.assigndelivery, name='assigndelivery'),
    # path('deliverylogout/', views.deliverylogout, name='deliverylogout'),
    path('mark_delivered/<int:assignment_id>/', views.mark_delivered, name='mark_delivered'),
    path('delivered_orders/', views.delivered_orders, name='delivered_orders'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedbacklist/', views.feedbacklist, name='feedbacklist'),
]
