# Generated by Django 5.2.2 on 2025-06-23 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
