# Generated by Django 5.2.2 on 2025-06-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantique.sproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantique.reg')),
            ],
        ),
    ]
