# Generated by Django 5.2.2 on 2025-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0007_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='dreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(upload_to='image/')),
                ('phone', models.CharField(max_length=15)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
