# Generated by Django 5.2.2 on 2025-07-12 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0009_deliveryperson_delete_dreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
        migrations.AddField(
            model_name='buy',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buy',
            name='ordered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
