# Generated by Django 5.2.2 on 2025-07-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0010_delete_deliveryperson_buy_assigned_buy_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='ordered_at',
        ),
    ]
