# Generated by Django 5.2.2 on 2025-07-12 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0012_buy_assigned_buy_ordered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantique.buy')),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantique.deliveryperson')),
            ],
        ),
    ]
