# Generated by Django 5.2.2 on 2025-07-12 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantique', '0013_deliveryperson_assigneddelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveredRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plantique.assigneddelivery')),
            ],
        ),
    ]
